

val fatalWarnings = SettingKey[Boolean]("fatalWarnings", "If true all warnings are errors")

fatalWarnings := false

name := """mockup-server"""

version := "1.0-SNAPSHOT"

lazy val mockup = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  jdbc,
  cache,
  ws,
  "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.1" % Test
)

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

// Wart remover: find bad patterns in scala code

wartremoverWarnings in(Compile, compile) ++= Warts.unsafe
wartremoverWarnings in(Compile, compile) ++= Seq(
  PlayWart.AssetsObject,
  PlayWart.CookiesPartial,
  PlayWart.FlashPartial,
  PlayWart.FormPartial,
  PlayWart.HeadersPartial,
  PlayWart.JavaApi,
  PlayWart.JsLookupResultPartial,
  PlayWart.JsReadablePartial,
  PlayWart.LangObject,
  PlayWart.MessagesObject,
  PlayWart.PlayGlobalExecutionContext,
  PlayWart.SessionPartial,
  PlayWart.WSResponsePartial)

// Bonus Warts
wartremoverWarnings in(Compile, compile) ++= Seq(
  PlayWart.DateFormatPartial,
  PlayWart.FutureObject,
  PlayWart.GenMapLikePartial,
  PlayWart.GenTraversableLikeOps,
  PlayWart.GenTraversableOnceOps,
  PlayWart.OptionPartial,
  PlayWart.ScalaGlobalExecutionContext,
  PlayWart.StringOpsPartial)

// exclude scala files generated by the play routes plugin
wartremoverExcluded ++= {
  val routesSources: File = crossTarget.value / "routes" / "main"

  Seq(
    routesSources / "controllers" / "ReverseRoutes.scala",
    routesSources / "controllers" / "javascript" / "JavaScriptReverseRoutes.scala",
    routesSources / "router" / "Routes.scala",
    routesSources / "router" / "RoutesPrefix.scala"
  )
}

wartremoverErrors in(Compile, compile) := {
  if (fatalWarnings.value)
    wartremoverWarnings.in(Compile, compile).value
  else
    Seq.empty
}

// For people how using coursier instant of ivy
wartremoverClasspaths += {
  val home = Path.userHome.getAbsolutePath

  s"file:$home/.coursier/cache/v1/https/repo1.maven.org/maven2/org/danielnixon/playwarts_2.11/0.24/playwarts_2.11-0.24.jar"
}

